### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by l4n-socrates** [hassio-addons/addon-home-panel#11]
Is there any option to change the language, or any plans to implement this feature?

e.g., weather text, days, month, etc.

**Comment by timmo001** [comment]
No, not in the near future. 80% of the app is user configured so most of it can be another language.

If there are multiple contributors and there is a need for other languages, I might reconsider. But for now, as the only developer on the project, this is just out of scope.

Thanks.

_Also, in future, open an issue on the main repo instead of the addon repo 👍_

_https://github.com/timmo001/home-panel_
