### ISSUE TITLE
Please allow using LLT for logging in

### ISSUE THREAD

**Issue by sagilo** [hassio-addons/addon-home-panel#17]
I'm using iPad2 for HomePanel (or at least want to), looks like it's not possible to provide access to HomePanel using frontend ES5.  
My suggestion is you provide an option to login using long live token, (similar to [TileBoard](https://github.com/resoai/TileBoard))

Thank you

**Comment by timmo001** [comment]
Please don't open issues in this repository if the issue is not related to the add-on itself.

Also, tokens are not used in this app. It is an implementation of the home-assistant/home-assistant-websocket that connects this app to Home Assistant. 

Please see my last comment on the issue you posted in the upstream. I will be unable to add support for older browsers at this time. Thanks

https://github.com/timmo001/home-panel/issues/272#issuecomment-485449086
