### ISSUE TITLE
Entered incorrect URL for hassio on install, now can't change

### ISSUE THREAD

**Issue by marl-scot** [hassio-addons/addon-home-panel#59]
# Problem/Motivation

On inital install of home-panel, i entered the wrong URL for connecting to hassio, now not able to change it.
reinstalled HP, don't have option to enter login details for HA.
Previous issue states to delete the cookies, uninstalled HP, deleted all cookies for HA domain, re-installed HP, still not able to update HA URL

## Expected behavior

Have an option to re-enter the HA URL and user/pass

## Actual behavior

Setting not changeable after inital setup

## Steps to reproduce

Enter incorrect URL for HA when setting up HP initially.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by mkotek** [comment]
Same here

**Comment by jressel01** [comment]
Workaround:
Open Web UI
Logout and create a new User. 
Now you can set the homeassistant URL for this User

**Comment by dpedestrian** [comment]
I ran into the same thing. I was unable to find in the docs how to revert all configuration to fresh. On another note, after setting correct url it failed to login to homeassistant and is now in a loop again but faster. There has to be a way to reset configuration properly.

**Comment by pfinnigan** [comment]
I too have run into the same problem. After I got the rapid loop I put log: debug on and did not get anything extra in the logs just a load of HTTP 304/200/101 messages with just too little for me to know what is going on. Then I searched for answers, a little late I fear. 

Stopping and starting the add-on in Home Assistant has no effect on the next restart the loop starts as soon as you visit the site.

I also tried uninstall/install. This resulted in a 504 error which I had seen on first install, but ignored:

<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.16.1</center> </body> </html>

Is that because I already have Nginx proxy add-on installed? Nothing in the documentation about this but eventually a Home Panel add-on is shown in my Supervisor Dashboard. 

I leave the default config, I use SSL with the the default locations for my certs, and I press start. Once started I flick the switch to add this add-on to my side bar. I use that to get in. I use the same user ID again and the loop starts immediately.

Where have I gone wrong.

**Comment by pfinnigan** [comment]
I am sorry for above. I have intended that the <title> session etc should be in a code block I forgot to add like this:

`<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.16.1</center> </body> </html>`

**Comment by sinclairpaul** [comment]
Try clearing your browser cache for the site, in all honesty this should likely be logged at https://github.com/timmo001/home-panel
